//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryImage
    {
        public int Id { get; set; }
        public string ImageTitle { get; set; }
        public string ImagePath { get; set; }
        public int FolderId { get; set; }
    
        public virtual GalleryFolder GalleryFolder { get; set; }
    }
}
